FROM maild_base

LABEL maintainer="Sergiu Giurgiu <sgiurgiu11@gmail.com>"

COPY maild_web.conf /etc/maild/
COPY private.key /etc/maild/
COPY dhparams.pem /etc/maild/
COPY certificate.crt /etc/maild/

ENTRYPOINT ["/usr/bin/maild_web", "-c", "/etc/maild/maild_web.conf"]
EXPOSE 8443
